#include "RomiRobot/RomiRobot.h"

// These variables are autogenerated and compiled
// into the library by the version.cmake script
extern const char* GIT_TAG;
extern const char* GIT_REV;
extern const char* GIT_BRANCH;

const char* romirobot_git_version(void) {
  return GIT_TAG;
}

const char* romirobot_git_revision(void) {
  return GIT_REV;
}

const char* romirobot_git_branch(void) {
  return GIT_BRANCH;
}

int add_one(int x) {
  return x + 1;
}
